apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
  annotations:
    iam.gke.io/gcp-service-account: 261248090722-compute@developer.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - apiGroups: ["", "batch"]
    resources:
      - pods
      - jobs
      - pods/log
    verbs:
      - get
      - list
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
