apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: continuumio/miniconda3
        command: ["echo",  "Hello World."]
      restartPolicy: Never
  backoffLimit: 4
