apiVersion: batch/v1
kind: Job
metadata:
  name: {{name}}
spec:
  template:
    spec:
      containers:
      - name: {{name}}
        image: {{image}}
        command:
        - python
        - -c
        - |
          {{script}}
      restartPolicy: Never
  backoffLimit: 1
