from setuptools import setup

setup(
    name='sk8s',
    version='0.1.0',    
    description='Run python functions on Kubernetes',
    url='https://github.com/jared-maguire/jobs',
    author='Jared Maguire',
    author_email='jared.maguire@gmail.com',
    license='MIT',
    packages=['sk8s'],
    install_requires=['dill',
                      'requests',
                      'jinja2',
                      'pyyaml',
                      'pytest',
                      'pytest-xdist',
                      'numpy',
                      'scipy',
                      'pandas',
                      ],
    package_dir={'sk8s': 'sk8s'},
    package_data={'sk8s': ['sk8s/*.yaml',
                           'sk8s/*.txt',
                           'sk8s/*.template']},
    include_package_data=True,
    classifiers=[
        #'Development Status :: 1 - Planning',
        #'Intended Audience :: Science/Research',
        #'License :: OSI Approved :: BSD License',  
        #'Operating System :: POSIX :: Linux',        
        #'Programming Language :: Python :: 2',
        #'Programming Language :: Python :: 2.7',
        #'Programming Language :: Python :: 3',
        #'Programming Language :: Python :: 3.4',
        #'Programming Language :: Python :: 3.5',
    ],
)