apiVersion: batch/v1
kind: Job
metadata:
  name: job-jqide
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Balanced"
      serviceAccountName: internal-kubectl
      containers:
      - name: worker
        image: gcr.io/jared-genome-analysis/ngs-1
        imagePullPolicy: Always
        command:
        - python
        - -c
        - |
          import dill as pickle
          import base64
          import json
          import sys
          import sk8s

          func = sk8s.deserialize_func("gASVUgQAAAAAAACMCmRpbGwuX2RpbGyUjBBfY3JlYXRlX2Z1bmN0aW9ulJOUKGgAjAxfY3JlYXRlX2NvZGWUk5QoQwCUSwFLAEsASwFLAksTQwiIAHwAjgBTAJROhZQpjAFhlIWUjChjOlxVc2Vyc1xqYXJlZFxEZXNrdG9wXGpvYnNcc2s4c1xqb2JzLnB5lIwIPGxhbWJkYT6US35DAggAlIwEZnVuY5SFlCl0lFKUfZSMCF9fbmFtZV9flIwJc2s4cy5qb2JzlHNoC4wbZ3M6Ly9qYXJlZC1nZW5vbWUvamFyZWQuYmFtlIwpZ3M6Ly9qYXJlZC1nZW5vbWUvamFyZWRfaW50ZXJsZWF2ZWQuZnEuZ3qUhpSFlGgAjAxfY3JlYXRlX2NlbGyUk5ROhZRSlIWUdJRSlH2UfZQojA9fX2Fubm90YXRpb25zX1+UfZSMDF9fcXVhbG5hbWVfX5SMFXJ1bi48bG9jYWxzPi48bGFtYmRhPpR1hpRijAhidWlsdGluc5SMB2dldGF0dHKUk5SMBGRpbGyUjAVfZGlsbJSTlIwIX3NldGF0dHKUaCaMB3NldGF0dHKUk5SHlFKUaBuMDWNlbGxfY29udGVudHOUaAIoaAQoQw4AAQgBDAgQAQgBCAEOAZRLAksASwBLA0sESwNDRmQBZABsAIkAhwBmAWQCZAOECH0CfAJkBHwAmwBkBZ0DgwEBAHwCZAaDAQEAfAJkB4MBAQB8AmQIfAGbAJ0CgwEBAHQBUwCUKE5LAGgEKEMSAAEGAQIBAgEEAQQBAvsEBQL7lEsBSwBLAEsBSwhLE0MciABqAHwAZAFkAYgAagGIAGoCZAJkA40GagNTAJQoToiMBXV0Zi04lCiMBWNoZWNrlIwFc2hlbGyUjAZzdGRvdXSUjAZzdGRlcnKUjAhlbmNvZGluZ5R0lHSUKIwDcnVulIwEUElQRZSMBlNURE9VVJRoOXSUjANjbWSUhZSMPkM6XFVzZXJzXGphcmVkXEFwcERhdGFcTG9jYWxcVGVtcFxpcHlrZXJuZWxfODcyNFwzNDQ4NjE1ODU4LnB5lGg+SwNDEgYBAgECAQQBBAECAQT7AgUC+5SMCnN1YnByb2Nlc3OUhZQpdJRSlIwYZ2VuZXJhdGVfZnEuPGxvY2Fscz4ucnVulIwKZ3N1dGlsIGNwIJSMCSAuL2luLmJhbZSMG3NhbXRvb2xzIGNvbGxhdGUgaW4uYmFtIG91dJSMIHNhbXRvb2xzIGZhc3RxIC0wIG91dC5mcSBvdXQuYmFtlIwUZ3N1dGlsIGNwIG91dC5mcS5neiCUdJRoRowKb3V0cHV0X2JhbZSGlIwDYmFtlIwJb3V0cHV0X2ZxlGg+h5RoRIwLZ2VuZXJhdGVfZnGUSwFDDggBDAEQCAgBCAEOAQQBlCloR3SUUpR9lGgSjAhfX21haW5fX5RzaFZOTnSUUpR9lH2UaCF9lHOGlGKHlFIwLg==")

          config = {'docker_image_prefix': 'gcr.io/jared-genome-analysis/', 'docker_default_pull_policy': 'Always', 'docker_build_default_push_policy': True, 'default_storageclass': 'standard', 'default_readwritemany_storageclass': 'standard-rwx'}
          sk8s.configs.save_config(config)

          try:
              json.dump(func(), sys.stdout)
          except Exception as e:
              raise e
        resources:
            limits:
                ephemeral-storage: 1Ti
                memory: 4Gi

      restartPolicy: Never
  backoffLimit: 0
